# A generic Alembic configuration file.
[alembic]
# path to migration scripts
script_location = BackEnd/alembic

# A custom variable pointing to the .env file
dotenv_path = BackEnd/.env

# template for migration file names
file_template = %%(rev)s_%%(slug)s

# sys.path path, will be prepended to sys.path if present.
# ... add zipped folders, etc. here
# prepend_sys_path = .

# timezone for logging, etc.
# timezone =

# title for version file headers
# version_header_template =

# available drivers are sqlalchemy, alembic
# driver = sqlalchemy

# ... etc.

[post_write_hooks]
# post_write_hooks defines scripts or Python functions that are run
# on newly generated migration scripts.
# format is a CSV list of hook directives, where each directive is of the
# form 'hookname:path.to.hook'.
# hooks =
# hookname.arg1 = value1
# hookname.arg2 = value2

[loggers]
keys = root,sqlalchemy,alembic

[handlers]
keys = console

[formatters]
keys = generic

[logger_root]
level = WARN
handlers = console
qualname =

[logger_sqlalchemy]
level = WARN
handlers =
qualname = sqlalchemy.engine

[logger_alembic]
level = INFO
handlers =
qualname = alembic

[handler_console]
class = StreamHandler
args = (sys.stderr,)
level = NOTSET
formatter = generic

[formatter_generic]
format = %(levelname)-5.5s [%(name)s] %(message)s
datefmt = %H:%M:%S
