# docker-compose.yml
services:
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: konekte_user
      POSTGRES_PASSWORD: Nap_lite
      POSTGRES_DB: konekte_db
    ports:
      - "5432:5432" # Mappe le port par défaut de PostgreSQL
    volumes:
      - postgres_data:/var/lib/postgresql/data

  cache:
    image: redis:6.2-alpine
    restart: always
    command: redis-server --requirepass ${REDIS_PASSWORD:-your_default_redis_password}
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD:-your_default_redis_password}
    ports:
      - "6379:6379"
    volumes:
      - cache_data:/data

volumes:
  postgres_data:
  cache_data:
