"""Initial schema

Revision ID: ed7903abf9b2
Revises: 
Create Date: 2025-11-05 19:14:20.767757

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ed7903abf9b2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_interaction_profil_id', table_name='interaction')
    op.drop_index('ix_interaction_user_id', table_name='interaction')
    op.drop_table('interaction')
    op.drop_index('ix_preference_user_id', table_name='preference')
    op.drop_table('preference')
    op.drop_table('message')
    op.drop_index('ix_photo_url', table_name='photo')
    op.drop_index('ix_photo_user_id', table_name='photo')
    op.drop_table('photo')
    op.drop_index('ix_match_user1_id', table_name='match')
    op.drop_index('ix_match_user2_id', table_name='match')
    op.drop_table('match')
    op.drop_index('ix_user_email', table_name='user')
    op.drop_index('ix_user_latitude', table_name='user')
    op.drop_index('ix_user_longitude', table_name='user')
    op.drop_index('ix_user_username', table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('nom', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('username', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('birthdate', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('latitude', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('longitude', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('last_seen', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('gender', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('orientation', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('fcm_token', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('user_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('hashed_password', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='user_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_user_username', 'user', ['username'], unique=False)
    op.create_index('ix_user_longitude', 'user', ['longitude'], unique=False)
    op.create_index('ix_user_latitude', 'user', ['latitude'], unique=False)
    op.create_index('ix_user_email', 'user', ['email'], unique=False)
    op.create_table('match',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('match_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('user1_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user2_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user1_id'], ['user.id'], name='match_user1_id_fkey'),
    sa.ForeignKeyConstraint(['user2_id'], ['user.id'], name='match_user2_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='match_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_match_user2_id', 'match', ['user2_id'], unique=False)
    op.create_index('ix_match_user1_id', 'match', ['user1_id'], unique=False)
    op.create_table('photo',
    sa.Column('url', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('order', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='photo_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='photo_pkey')
    )
    op.create_index('ix_photo_user_id', 'photo', ['user_id'], unique=False)
    op.create_index('ix_photo_url', 'photo', ['url'], unique=False)
    op.create_table('message',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('match_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('sender_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('text', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('is_read', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['match_id'], ['match.id'], name='message_match_id_fkey'),
    sa.ForeignKeyConstraint(['sender_id'], ['user.id'], name='message_sender_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='message_pkey')
    )
    op.create_table('preference',
    sa.Column('min_age', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('max_age', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('max_distance_km', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('target_gender', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='preference_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='preference_pkey')
    )
    op.create_index('ix_preference_user_id', 'preference', ['user_id'], unique=False)
    op.create_table('interaction',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('profil_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('action', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['profil_id'], ['user.id'], name='interaction_profil_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='interaction_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='interaction_pkey')
    )
    op.create_index('ix_interaction_user_id', 'interaction', ['user_id'], unique=False)
    op.create_index('ix_interaction_profil_id', 'interaction', ['profil_id'], unique=False)
    # ### end Alembic commands ###
